name: Test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-action:
        name: Run action
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm run test
              env:
                ORG_ID: ${{ secrets.ORG_ID }}
                REGION: ${{ secrets.REGION }}
                API_KEY: ${{ secrets.API_KEY }}
                USER_EMAIL: ${{ secrets.USER_EMAIL }}
                USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
                DRIVER_EMAIL: ${{ secrets.DRIVER_EMAIL }}
                DRIVER_PASSWORD: ${{ secrets.DRIVER_PASSWORD }}

